# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f05a68dba95dcf8d6f0b40e43c7484130fa80dac6638aec299a582721c3c5ed3985827dbee90a50b26a23c6353ef1ef216c57671906b578ab13cccab338d15b2

test:
  secret_key_base: a0257e05e40fbedc4ae0b5d99475a4e0bb9019d1c2a5575f3c263c1724c695bbe33501d8313c0dec0bfe3b4a508fa1ffffff4a3b04513d87d009294af22365f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
